### ISSUE TITLE
Decide on license for distributing this resource

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#1]

**Comment by sublimemarch** [comment]
Because this isn't a work of code, a Creative Commons license is appropriate. I'd prefer [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by thejessleigh** [comment]
PR opened with markdown formatted Attribution-NonCommercial-ShareAlike 4.0 International

**Comment by sublimemarch** [comment]
Closed in #5
