### ISSUE TITLE
Add link defining emotional labor to step 0

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#11]

**Comment by sublimemarch** [comment]
Doing some research, I'm unsure if emotional labor is the correct phrase we should use in this context. I know it's come to mean "doing emotional work", but it originally meant having to regulate one's emotions as part of a job. Any thoughts?

https://en.wikipedia.org/wiki/Emotional_labor

**Comment by thejessleigh** [comment]
That's a really good point. I'm not sure I know of a better succinct phrase to describe it, but I will definitely think on it. Let me know if you come up with any ideas!

**Comment by carlydotwebsite** [comment]
Something like "emotional bandwidth" might get across the same idea?

**Comment by thejessleigh** [comment]
Closed with wording change #25 per discussion here. Unless anyone things that we should add further explanation about this?
