### ISSUE TITLE
Add glossary of terms?

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#20]
Not exactly sure where in this document it should live, but having a glossary for things like

- emotional labor
- sexism
- racism
- privilige
- transgender
- class
- race vs ethnicity
- etc

Might be super useful. Maybe an appendix? Definitely open to hearing thoughts on this.

**Comment by KaraAJC** [comment]
I'd love to make this happen! Have a buuuunch of terms from teaching about D&I... 

any further thoughts on implementation? Could be a quick MD file for now, and a larger "submit a term" feature later

**Comment by carlydotwebsite** [comment]
Yeah, I think putting it in something like a glossary.md file would probably be good for now—we can add a link to it from the main content file.

**Comment by KaraAJC** [comment]
woohoo! happening!

**Comment by sublimemarch** [comment]
Closed by PR: https://github.com/stephmarx/so-you-just-learned/pull/30
