### ISSUE TITLE
Link to Glossary of terms on main README

### ISSUE THREAD

**Issue by sublimemarch** [sublimemarch/so-you-just-learned#31]
We have an awesome new glossary of terms (/glossary.md), so we should link to it from the README.

I'm thinking this should maybe go in Step 0. Maybe add a sentence like "Be sure to check out our glossary" with a link?

**Comment by carlydotwebsite** [comment]
Yeah—eventually we might want some kind of navigation section if we have additional subpages or something like that? But yeah, Step 0 seems like a good place to put it.

**Comment by nikkilr88** [comment]
https://github.com/stephmarx/so-you-just-learned/pull/40

**Comment by sublimemarch** [comment]
Closed by #40
