### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by sublimemarch** [sublimemarch/so-you-just-learned#33]
I think we should add a description of our PR review process, which I suggest which formalize as:

1. Submit a PR, tagging which issue it closes if relevant
2. The three maintainers are assigned
3. If 2/3 maintainers approve, we merge the PR.

I also think we should add a short description of the labels I just added, which are:
- "good for new folks" - We welcome new contributors to help with any issue, and we've tagged some issues as specifically being easily approachable for new contributors. These might include adding links, fixing typos, or other small changes that don't require lots of discussion.
- "discussion requested" - This means that a maintainer or the person who reported the issue as requested discussion about the issue. This might include discussing the best way to write something or how to approach including a new link, for example.

**Comment by thejessleigh** [comment]
I have a little bit of free time this afternoon. I'll try to get this knocked out.

**Comment by sublimemarch** [comment]
@thejessleigh just for future reference, make sure to put "Closes #(issue number)" in your PR to have it auto-close when we merge the PR.
