### ISSUE TITLE
Link to conrtibuting.md

### ISSUE THREAD

**Issue by sublimemarch** [sublimemarch/so-you-just-learned#34]
Probably add a link at the bottom of the document, saying something like: "Have you found this resource useful? Help us by contributing!"

**Comment by nikkilr88** [comment]
I think I did it correctly... :D I'm still figuring all of this out.
https://github.com/stephmarx/so-you-just-learned/pull/36

**Comment by thejessleigh** [comment]
Closed via #36

**Comment by sublimemarch** [comment]
Thanks so much for your contribution! 💖
