### ISSUE TITLE
Fix formatting issue in code_of_conduct.md

### ISSUE THREAD

**Issue by carlydotwebsite** [sublimemarch/so-you-just-learned#35]
Somehow Jess's name, linked to her email, ended up as a sentence on its own. (Should probably be linked to "contacting the project team" instead?)

**Comment by thejessleigh** [comment]
Ah yeah. I think I just substituted in for whatever the boilerplate was, and I didn't feel comfortable volunteering anyone else's email publicly. Should definitely be fixed so it's more readable.

**Comment by nikkilr88** [comment]
https://github.com/stephmarx/so-you-just-learned/pull/42

I have a question. Before reformatting, I tried to click the e-mail link, but nothing popped up. Is this my browser or was there a syntax error to begin with?

**Comment by sublimemarch** [comment]
Currently, it's a mailto: link. If you have something on your computer set to not open mailto: links for some reason, you wouldn't see anything pop up.

**Comment by sublimemarch** [comment]
Looks like this issue was resolved but never closed. Closing it now!
