### ISSUE TITLE
Change "Emotional Labor" section heading

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#39]
These aren't all strictly emotional labor, and I know we've been trying to get better about correctly using that term. Maybe something like "invisible labor" would be better? I'm not really sure the best way to phrase it, but I want to make sure we're deliberate and thoughtful about the terms we use.

**Comment by carlydotwebsite** [comment]
Yeah, a lot of those articles fall into more of a category of "derailing/disingenuous conversation", and the other part is more like... division of labor/second shift concerns? I'm not sure what name to give these categories, though, since nothing I'm coming up with is very pithy.

**Comment by sublimemarch** [comment]
Closed by #49
