### ISSUE TITLE
Add something on codes of conduct

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#51]
Adding a link to step 1 about the necessity of codes of conduct (and consistent enforcement) would be a good, tech specific addition to this resource.

**Comment by catheraaine** [comment]
I like this resource! 

https://alistapart.com/article/tweaking-the-moral-ui

It also links to this! 
http://incisive.nu/2014/codes-of-conduct/

**Comment by thejessleigh** [comment]
closed via #64
