### ISSUE TITLE
Only Maintainers can assign people to a pull request

### ISSUE THREAD

**Issue by AdiraSlat** [sublimemarch/so-you-just-learned#56]
Contributing.md states that if you are submitting a pull request that you should assign all of the maintainers to the PR so that they can see and review it. As a non-Maintainer, I am unable to assign people to my PR.

**Comment by thejessleigh** [comment]
Oh, good call. Thanks!

**Comment by sublimemarch** [comment]
Do we want to change this to instead say that you should tag the maintainers in the pull request, and list our github handles?

**Comment by thejessleigh** [comment]
Oh, I also checked here to see if there was an issue open :P. I'll change the documentation tonight.

**Comment by thejessleigh** [comment]
Closed as of #58
