### ISSUE TITLE
Come up with resources for Step 3

### ISSUE THREAD

**Issue by thejessleigh** [sublimemarch/so-you-just-learned#8]

**Comment by sublimemarch** [comment]
Do we want to develop a list of folks to follow on Twitter? Publications? Podcasts?

**Comment by thejessleigh** [comment]
Sure. I can start thinking of things and list them here.

**Comment by thejessleigh** [comment]
I've added a few podcasts to Step 3 in PR #18. I think we still need more, but maybe after 18 is merged we can close this issue and treat new additions as discrete issues?
